In [1]:
# install tensorflow using pip
# pip3 install tensorflow 
# or 
# # pip3 install tensorflow-gpu

In [2]:
# if you want to skip local installation, use cocalc.com
# sign-up with GitHub/Google
# 1) create new project
# 2) choose JupyterNotebook as type
# 3) go to "Kernel" menu, and choose Python 3 (Anaconda)
# Now you have an IpythonPython Notebook with tensorflow installed, running in the Cloud

In [3]:
# let's import tensorflow as tf
import tensorflow as tf

In [4]:
# let's look at tensorflow types

In [5]:
# constants in tensorflow are variables that contain fixed values given on their creation
V1 = tf.constant([1.,2.])
# you can also pass explicit names 
V2 = tf.constant([3.,4.], name='const_V2')

In [6]:
# name arguments are useful if you want to save your variables to a binary file
# they are also used in TensorBoard, a visual representation of Tensorflow calculations (we will get to it later)

In [7]:
# these types produce tensors, tensor is a typed multy-dimensional array
print(V1)
print(V2)

Tensor("Const:0", shape=(2,), dtype=float32)
Tensor("const_V2:0", shape=(2,), dtype=float32)


In [8]:
# you can then conduct various operations on your tensors
V3 = V1 + V2
V4 = V1 * V2
print(V3)
print(V4)

Tensor("add:0", shape=(2,), dtype=float32)
Tensor("mul:0", shape=(2,), dtype=float32)


In [9]:
# the results won't be calculated, you need to call .eval() first
V3.eval()
V4.eval()

ValueError: Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`

In [10]:
# that didn't work, all operations are evaluated within sessions
# let's create a session first
sess = tf.Session()

In [11]:
V3 = V1 + V2
print(V3)
V4 = V1 * V2
print(V4)

Tensor("add_1:0", shape=(2,), dtype=float32)
Tensor("mul_1:0", shape=(2,), dtype=float32)


In [12]:
V3.eval(session=sess)

array([ 4.,  6.], dtype=float32)

In [13]:
V4.eval(session=sess)

array([ 3.,  8.], dtype=float32)

In [14]:
# close the session
sess.close()

In [15]:
# interactive sessions can save you a lot of time
sess = tf.InteractiveSession()

In [16]:
V3 = V1 + V2
V4 = V1 * V2

In [17]:
# now we don't need to care about passing sessions
V3.eval()

array([ 4.,  6.], dtype=float32)

In [18]:
# working with placeholders
import numpy as np
# basically, we define the size and what the input type is
# at run time we initialize placeholders with data
x = tf.placeholder(tf.float32, shape=(1024, 1024))
y = tf.matmul(x, x)

In [19]:
# create a random array
rand_array = np.random.rand(1024, 1024)

In [20]:
# feed x with values
# this can only be done within sess.run(), the values are fed with "feed_dict" argument
print(sess.run(y, feed_dict={x: rand_array}))

[[ 244.18894958  250.5344696   245.63404846 ...,  245.30279541
   261.00485229  246.15307617]
 [ 244.99571228  247.22982788  253.37451172 ...,  249.89782715
   272.07046509  255.60710144]
 [ 245.66329956  247.06752014  243.223526   ...,  243.88070679
   260.42645264  249.35879517]
 ..., 
 [ 249.91656494  247.9967804   246.56007385 ...,  251.73240662
   268.06588745  254.38095093]
 [ 259.34509277  257.17706299  263.76843262 ...,  263.28378296
   275.79354858  264.26629639]
 [ 250.10473633  250.99487305  246.12312317 ...,  245.54460144
   263.52578735  251.38690186]]


In [21]:
# another data type in Tensorflow in tf.Variable
# these are not constant, the values can be changed using .assign() method
w = tf.Variable([1.,3.], name='variable_w')

In [22]:
w.assign(w + 1.1)  # or w.assign_add(.1)

<tf.Tensor 'Assign:0' shape=(2,) dtype=float32_ref>

In [23]:
# now how do I get the value of w?

In [24]:
# we would need to initialize our w Variable for it to be used in our computations

In [25]:
# let's launch the graph in a session
with tf.Session() as sess:
    sess.run(w.initializer)
    print(w.eval())

[ 1.  3.]


In [26]:
# our w wasn't changed
# it needs to be initialized before we assign new values to it
with tf.Session() as sess:
    sess.run(w.initializer)
    print(w.assign(w + .1).eval())
    print(w.eval())

[ 1.10000002  3.0999999 ]
[ 1.10000002  3.0999999 ]


In [27]:
# what if we have multiple variables, do we have to initialize each of them?
w = tf.Variable([1.,3.], name='variable_1')
w2 = tf.Variable([2.,4.], name='variable_2')

In [28]:
# of course not, we can add an operation to initialize all variables we might have
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op)
    print(w.eval())
    print(w2.eval())

[ 1.  3.]
[ 2.  4.]


In [29]:
sess = tf.InteractiveSession()

In [30]:
# Python tensorflow, has all the same caveats Python has
a = tf.constant(23)
b = tf.constant(11)
c = tf.div(a,b)

In [31]:
# what will this evaluate to?
c.eval()

2

In [32]:
# use truediv
c = tf.truediv(a,b)
c.eval()

2.0909090909090908

In [33]:
# The computations in Tensorflow are saved as Directed graphs

In [34]:
from IPython.display import Image
Image(url='https://www.tensorflow.org/images/tensors_flowing.gif')

In [35]:
# to visualize your graphs, you can use TensorBoard
# the name arguments are used here to help you identify your variables
# and this helps you take a more detailed look into the computations your Deep Learning model is going through

In [36]:
from IPython.display import Image
Image(url='https://www.tensorflow.org/images/graph_vis_animation.gif')

In [37]:
# you can define your values within scopes, to help declutter the visualization
# in TensorBoard all underlying variables will be collapsed under 'hidden' node label
with tf.name_scope('hidden') as scope:
  a = tf.constant(5, name='alpha')
  W = tf.Variable(tf.random_uniform([1, 2], -1.0, 1.0), name='weights')
  b = tf.Variable(tf.zeros([1]), name='biases')

In [38]:
# to start your TensorBoard, you would first need to dump your data to disk
writer = tf.summary.FileWriter("/tmp")
writer.add_graph(sess.graph)

In [39]:
# then run tensorboard from the terminal
# tensorboard --logdir /tmp

In [40]:
# but why not visualize it directly in our Jupyter Notebook?

In [41]:
# let's use this hacky way to do it!
# courtesy of Deepdream 
# https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/deepdream/deepdream.ipynb

from IPython.display import clear_output, Image, display, HTML

def strip_consts(graph_def, max_const_size=32):
    """Strip large constant values from graph_def."""
    strip_def = tf.GraphDef()
    for n0 in graph_def.node:
        n = strip_def.node.add() 
        n.MergeFrom(n0)
        if n.op == 'Const':
            tensor = n.attr['value'].tensor
            size = len(tensor.tensor_content)
            if size > max_const_size:
                tensor.tensor_content = "<stripped %d bytes>"%size
    return strip_def

def show_graph(graph_def, max_const_size=32):
    """Visualize TensorFlow graph."""
    if hasattr(graph_def, 'as_graph_def'):
        graph_def = graph_def.as_graph_def()
    strip_def = strip_consts(graph_def, max_const_size=max_const_size)
    code = """
        <script>
          function load() {{
            document.getElementById("{id}").pbtxt = {data};
          }}
        </script>
        <link rel="import" href="https://tensorboard.appspot.com/tf-graph-basic.build.html" onload=load()>
        <div style="height:600px">
          <tf-graph-basic id="{id}"></tf-graph-basic>
        </div>
    """.format(data=repr(str(strip_def)), id='graph'+str(np.random.rand()))

    iframe = """
        <iframe seamless style="width:1200px;height:620px;border:0" srcdoc="{}"></iframe>
    """.format(code.replace('"', '&quot;'))
    display(HTML(iframe))

In [42]:
# let's see what graphs we have logged today so far
show_graph(tf.get_default_graph().as_graph_def())

In [ ]:
# find out more about TensorBoard at https://www.youtube.com/watch?v=eBbEDRsCmv4

In [ ]:
# final ideas
# improving CPU performance: https://software.intel.com/en-us/articles/tensorflow-optimizations-on-modern-intel-architecture
# meet the tensorflow team on July 25. in Munich: https://www.meetup.com/Hacking-Machine-Learning/events/240095377/